### ISSUE TITLE
Issue explicit error on shim failure

### ISSUE THREAD

**Issue by garthk** [brunch/deppack#10]
If shimming `child_process`, `dns`, `fs`, `net` etc:
- `shimAliases` passes `undefined` to `generateFileBasedModuleName`
- … which passes it to `getModuleFullRootName`
- … which tries to call `path.split` despite `path` being `undefined`

The root cause is shimming the un-shimmable. Troubleshooting would be easier if `shimAliases`' reducer did something like:

``` js
const shim = shims.fileShims[x];
assert.notEqual(shim, undefined, `no shim available for ${x}`);
const mod = generateFileBasedModuleName(shim);
```

I can submit a PR for that if someone can confirm my theory about what's going on, here. I haven't yet given Brunch explicit instructions on how to behave. It strikes me it's inhaling my server-side modules as if they're client side.

**Comment by goshacmd** [comment]
Thanks for the report! The way to fix is to simply skip these shims as no alias is needed for these, because brunch will shim them to `{}` anyway.

I submitted https://github.com/brunch/deppack/pull/11 to address this.
