### ISSUE TITLE
`fcache.updateCache` is called on a directory

### ISSUE THREAD

**Issue by ferhatelmas** [brunch/deppack#26]
```
.../web/client/node_modules/brunch/lib/fs_utils/file_list.js:198
        if (error) throw new Error(formatError('Reading', error));
                   ^

Error: undefined of Error: EISDIR: illegal operation on a directory, read failed. 
  at .../web/client/node_modules/brunch/lib/fs_utils/file_list.js:198:26
  at .../web/client/node_modules/fcache/index.js:19:23
  at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:389:12)
```

From going brunch 2.6.0 to 2.6.1, only meaningful change is updated deppack. As far as I see,  #12 introduced this issue (no problem w/ 0.3.3).

Btw, thanks, rejuvenating brunch.

**Comment by goshacmd** [comment]
Does it work with Brunch 2.7.3 which uses deppack 0.4.1?

If it does indeed persist, could you isolate/narrow it down to a specific `require` call that introduces this?

**Comment by ferhatelmas** [comment]
No, it doesn't exist anymore, I will try to update for ~2.7. Thanks for responsiveness.
